from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(777, 502)
        MainWindow.setAutoFillBackground(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.push_button_1 = QtWidgets.QPushButton(self.centralwidget)
        self.push_button_1.setGeometry(QtCore.QRect(20, 160, 171, 71))
        self.push_button_1.setMouseTracking(False)
        self.push_button_1.setObjectName("push_button_1")
        self.push_button_2 = QtWidgets.QPushButton(self.centralwidget)
        self.push_button_2.setGeometry(QtCore.QRect(20, 260, 171, 71))
        self.push_button_2.setObjectName("push_button_2")
        self.push_button_3 = QtWidgets.QPushButton(self.centralwidget)
        self.push_button_3.setGeometry(QtCore.QRect(20, 360, 171, 71))
        self.push_button_3.setObjectName("push_button_3")
        self.user_score = QtWidgets.QLCDNumber(self.centralwidget)
        self.user_score.setGeometry(QtCore.QRect(40, 90, 171, 51))
        font = QtGui.QFont()
        font.setKerning(True)
        self.user_score.setFont(font)
        self.user_score.setMouseTracking(False)
        self.user_score.setAcceptDrops(False)
        self.user_score.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.user_score.setObjectName("user_score")
        self.comp_score = QtWidgets.QLCDNumber(self.centralwidget)
        self.comp_score.setGeometry(QtCore.QRect(460, 90, 171, 51))
        self.comp_score.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.comp_score.setObjectName("comp_score")
        self.comp_step = QtWidgets.QLabel(self.centralwidget)
        self.comp_step.setGeometry(QtCore.QRect(580, 160, 171, 271))
        self.comp_step.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.comp_step.setTextFormat(QtCore.Qt.AutoText)
        self.comp_step.setAlignment(QtCore.Qt.AlignCenter)
        self.comp_step.setWordWrap(False)
        self.comp_step.setObjectName("comp_step")
        self.count_of_bricks = QtWidgets.QLabel(self.centralwidget)
        self.count_of_bricks.setGeometry(QtCore.QRect(210, 40, 351, 71))
        self.count_of_bricks.setTextFormat(QtCore.Qt.AutoText)
        self.count_of_bricks.setAlignment(QtCore.Qt.AlignCenter)
        self.count_of_bricks.setWordWrap(False)
        self.count_of_bricks.setIndent(-1)
        self.count_of_bricks.setObjectName("count_of_bricks")
        self.user_icon = QtWidgets.QLabel(self.centralwidget)
        self.user_icon.setGeometry(QtCore.QRect(440, 160, 121, 271))
        self.user_icon.setText("")
        self.user_icon.setPixmap(QtGui.QPixmap("icons8-монитор-100.png"))
        self.user_icon.setObjectName("user_icon")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(210, 160, 121, 271))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("icons8-ios-100.png"))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setEnabled(True)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 777, 23))
        self.menubar.setAutoFillBackground(False)
        self.menubar.setDefaultUp(False)
        self.menubar.setNativeMenuBar(True)
        self.menubar.setObjectName("menubar")
        self.menu_exit = QtWidgets.QMenu(self.menubar)
        self.menu_exit.setObjectName("menu_exit")
        self.menu_files = QtWidgets.QMenu(self.menubar)
        self.menu_files.setObjectName("menu_files")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_logs = QtWidgets.QAction(MainWindow)
        self.action_logs.setCheckable(False)
        self.action_logs.setStatusTip("")
        self.action_logs.setWhatsThis("")
        self.action_logs.setObjectName("action_logs")
        self.action_stats = QtWidgets.QAction(MainWindow)
        self.action_stats.setObjectName("action_stats")
        self.menu_files.addAction(self.action_logs)
        self.menu_files.addAction(self.action_stats)
        self.menubar.addAction(self.menu_exit.menuAction())
        self.menubar.addAction(self.menu_files.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.push_button_1.setText(_translate("MainWindow", "1"))
        self.push_button_2.setText(_translate("MainWindow", "2"))
        self.push_button_3.setText(_translate("MainWindow", "3"))
        self.comp_step.setText(_translate("MainWindow", "TextLabel"))
        self.count_of_bricks.setText(_translate("MainWindow", "TextLabel"))
        self.menu_exit.setTitle(_translate("MainWindow", "Exit"))
        self.menu_files.setTitle(_translate("MainWindow", "Files"))
        self.action_logs.setText(_translate("MainWindow", "Logs"))
        self.action_logs.setToolTip(_translate("MainWindow", "Logs"))
        self.action_logs.setShortcut(_translate("MainWindow", "Ctrl+L"))
        self.action_stats.setText(_translate("MainWindow", "Stats"))
        self.action_stats.setToolTip(_translate("MainWindow", "Stats"))
        self.action_stats.setShortcut(_translate("MainWindow", "Ctrl+S"))
